apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: full-control-1
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "create", "update", "patch", "watch", "delete"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: full-control-1
subjects:
- kind: ServiceAccount
  name: newsa
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: full-control-1
  apiGroup: rbac.authorization.k8s.io
