apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: finance
  name: reader
rules:
- apiGroups: [""] # 
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]  
  resources: ["*"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: finance
subjects:
- kind: User
  name: john
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: reader 
  apiGroup: rbac.authorization.k8s.io
